# Generated by Django 2.0 on 2018-08-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landi1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
