# Generated by Django 2.0 on 2018-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landi1', '0002_post_clicked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clicked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
